# Generated by Django 3.2.12 on 2022-02-10 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='i_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.industrylist'),
        ),
    ]
